apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: d:\external_paths\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: authentication
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authentication
  template:
    metadata:
      annotations:
        kompose.cmd: d:\external_paths\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: authentication
    spec:
      containers:
        - image: authentication
          name: authentication
          ports:
            - containerPort: 9004
              protocol: TCP
      restartPolicy: Always
