apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: d:\external_paths\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: authentication
  name: authentication
spec:
  ports:
    - name: "9004"
      port: 9004
      targetPort: 9004
  selector:
    io.kompose.service: authentication
