apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: d:\external_paths\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: discovery
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery
  template:
    metadata:
      annotations:
        kompose.cmd: d:\external_paths\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: discovery
    spec:
      containers:
        - image: discovery
          name: discovery
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
