apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: d:\external_paths\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: listing
  name: listing
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    io.kompose.service: listing
