apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: d:\external_paths\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment
  template:
    metadata:
      annotations:
        kompose.cmd: d:\external_paths\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: payment
    spec:
      containers:
        - env:
            - name: RABBITMQ_HOST
              value: rabbitmq
          image: payment
          name: payment
          ports:
            - containerPort: 9005
              protocol: TCP
      restartPolicy: Always
