apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: d:\external_paths\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: reservation
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reservation
  template:
    metadata:
      annotations:
        kompose.cmd: d:\external_paths\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: reservation
    spec:
      containers:
        - env:
            - name: MONGODB_PASS
              value: root
          image: reservation
          name: reservation
          ports:
            - containerPort: 9003
              protocol: TCP
      restartPolicy: Always
